{"name": "Тест на получение ошибки приняти заказа с неверным id заказа", "status": "passed", "start": 1745072124038, "stop": 1745072124444, "uuid": "33c44562-a032-4442-b2e1-d363bd39598a", "historyId": "7633646bfe1706637a3a315ff5367d1a", "testCaseId": "7633646bfe1706637a3a315ff5367d1a", "fullName": "tests.test_accept_the_order.TestAcceptOrder#test_accept_order_invalid_order_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_the_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "LAPTOP-3QFAQEQR"}, {"name": "thread", "value": "10504-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_the_order"}]}