{"name": "Тест получение ошибки при запросе c несуществующим номером заказа", "status": "passed", "start": 1745072126870, "stop": 1745072127005, "uuid": "90dff034-bf19-444e-88d4-0de1db4d804e", "historyId": "ac19d7ce8adbe2e8eef19e0943ef0381", "testCaseId": "ac19d7ce8adbe2e8eef19e0943ef0381", "fullName": "tests.test_get_order_by_number.TestGetOrderByNomber#test_invalid_nomber_order", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order_by_number"}, {"name": "subSuite", "value": "TestGetOrderByNomber"}, {"name": "host", "value": "LAPTOP-3QFAQEQR"}, {"name": "thread", "value": "10504-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_by_number"}]}