{"name": "Тест на получение ошибки приняти заказа с неверным id заказа", "status": "passed", "start": 1745008114308, "stop": 1745008114674, "uuid": "a3d59ece-4466-4ea1-b834-96b2ed619e67", "historyId": "7633646bfe1706637a3a315ff5367d1a", "testCaseId": "7633646bfe1706637a3a315ff5367d1a", "fullName": "tests.test_accept_the_order.TestAcceptOrder#test_accept_order_invalid_order_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_the_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "LAPTOP-3QFAQEQR"}, {"name": "thread", "value": "8104-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_the_order"}]}