{"name": "Тест на получение ошибки при авторизации с неверным паролем", "status": "passed", "description": "Создаем курьера и передаем на авторизацию только логин, код 404 и в теле ответа \"Учетная запись не найдена\"", "start": 1745008119475, "stop": 1745008119758, "uuid": "5268c409-94cc-4308-9cfe-ed83a177d41e", "historyId": "21c1d53bc979f783bac4718c2d5dcf99", "testCaseId": "21c1d53bc979f783bac4718c2d5dcf99", "fullName": "tests.test_login_courier.TestLoginCourier#test_create_duplicate_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "LAPTOP-3QFAQEQR"}, {"name": "thread", "value": "8104-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}